/**
 * Typography Tokens (Interactive)
 * Auto-generated by Type Lab
 */

export const CURRENT_TEXT = {
    "hero_en": "text-[clamp(30px,4vw,42px)] font-english font-bold uppercase tracking-widest text-[#05121C]",
    "nav_en": "text-[clamp(13px,0.8vw+10px,15px)] font-english font-bold tracking-wide uppercase",
    "badge": "text-[clamp(10px,0.68vw+7.82px,16px)] font-english font-bold leading-normal tracking-wide mt-0 mb-0 text-left text-[#2A4458] font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english uppercase",
    "badge_pill": "text-[clamp(8px,0.45vw+6.55px,12px)] font-english font-bold leading-none tracking-tighter mt-0 mb-0 text-left text-[#2A4458] font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english uppercase inline-flex items-center rounded-full border-[2px] border-[#2A4458] px-2 py-0.5",
    "page_title_ko": "text-[clamp(36px,5vw+16px,64px)] font-bold font-korean leading-[1.15] break-keep",
    "section_title_ko_display": "text-[clamp(56px,4.55vw+41.45px,96px)] font-korean font-bold leading-none tracking-normal text-[#05121C]",
    "section_heading_ko": "text-[clamp(18px,1.14vw+14.36px,28px)] font-mono font-bold leading-normal tracking-wide mb-3 text-[#05121C] break-keep",
    "notion_h1": "text-3xl font-bold mt-4 mb-2 font-korean text-[#05121C]",
    "notion_h3": "text-[16px] font-korean font-bold leading-tight tracking-wide mt-2 mb-1 text-left text-[#395163] text-xl",
    "bullet_list": "text-[clamp(12px,0.45vw+10.55px,16px)] font-korean font-normal leading-relaxed tracking-normal mb-0 text-left text-[#05121C] text-lg",
    "numbered_list": "text-[16px] font-korean font-light leading-loose tracking-normal mb-0 text-[#05121C] text-lg list-decimal ml-4",
    "quote": "text-lg leading-relaxed font-light font-mono text-[#374151] italic border-l-4 border-gray-300 pl-4",
    "callout": "text-lg leading-relaxed font-light font-mono text-[#05121C] p-4 bg-gray-100 rounded",
    "caption": "text-sm font-mono text-gray-500 mt-2 text-center",
    "reference_text": "text-[16px] font-korean font-bold leading-tight tracking-normal mt-0 mb-0 text-left text-[#2A4458] text-[0.85em]",
    "body_ko_default": "text-[clamp(16px,0.45vw+14.55px,20px)] font-korean font-light leading-relaxed tracking-normal mt-2 mb-2 text-left text-[#05121C] break-keep",
    "body_ko_long": "text-[clamp(16px,0.45vw+14.55px,20px)] font-mono font-light leading-loose tracking-normal mt-2 mb-2 text-left text-[#05121C] break-keep",
    "verse_text": "text-[clamp(17px,0.34vw+15.91px,20px)] font-korean font-light leading-relaxed tracking-normal mb-0 text-left text-[#05121C] break-keep",
    "verse_reference": "text-[16px] font-korean font-bold leading-normal tracking-normal mb-1 text-right text-[#2A4458] text-[0.85em]",
    "table_head": "text-[clamp(14px,0.11vw+13.64px,15px)] font-mono font-bold leading-normal tracking-normal mt-0 mb-0 text-left text-[#111827] font-english font-english font-english font-english font-english font-english font-english align-top py-4 px-3",
    "table_cell": "text-[clamp(14px,0.23vw+13.27px,16px)] font-korean font-normal leading-tight tracking-normal mt-0 mb-0 text-left text-[#2a4458] align-top py-4 px-3",
    "link_text": "text-[16px] font-korean font-medium leading-normal tracking-normal mt-0 mb-0 text-left text-[#2a4458] hover:opacity-80 transition-opacity cursor-pointer",
    "footer_contact_label": "font-mono font-bold text-[15px]",
    "footer_contact_value": "font-mono font-light text-[15px]",
    "summary_title": "text-[clamp(20px,1.36vw+15.64px,32px)] font-korean font-bold leading-snug tracking-normal mt-0 mb-0 text-left text-[#05121C] md:"
};

export const NEXT_TEXT = {
    "hero_en": "text-[clamp(30px,4vw,42px)] font-english font-bold uppercase tracking-widest text-[#05121C]",
    "nav_en": "text-[clamp(13px,0.8vw+10px,15px)] font-english font-bold tracking-wide uppercase",
    "badge": "text-[clamp(10px,0.68vw+7.82px,16px)] font-english font-bold leading-normal tracking-wide mt-0 mb-0 text-left text-[#2A4458] font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english uppercase",
    "badge_pill": "text-[clamp(8px,0.45vw+6.55px,12px)] font-english font-bold leading-none tracking-tighter mt-0 mb-0 text-left text-[#2A4458] font-english font-english font-english font-english font-english font-english font-english font-english font-english font-english uppercase inline-flex items-center rounded-full border-[2px] border-[#2A4458] px-2 py-0.5",
    "page_title_ko": "text-[clamp(36px,5vw+16px,64px)] font-bold font-korean leading-[1.15] break-keep",
    "section_title_ko_display": "text-[clamp(56px,4.55vw+41.45px,96px)] font-korean font-bold leading-none tracking-normal text-[#05121C]",
    "section_heading_ko": "text-[clamp(18px,1.14vw+14.36px,28px)] font-mono font-bold leading-normal tracking-wide mb-3 text-[#05121C] break-keep",
    "notion_h1": "text-3xl font-bold mt-4 mb-2 font-korean text-[#05121C]",
    "notion_h3": "text-[16px] font-korean font-bold leading-tight tracking-wide mt-2 mb-1 text-left text-[#395163] text-xl",
    "bullet_list": "text-[clamp(12px,0.45vw+10.55px,16px)] font-korean font-normal leading-relaxed tracking-normal mb-0 text-left text-[#05121C] text-lg",
    "numbered_list": "text-[16px] font-korean font-light leading-loose tracking-normal mb-0 text-[#05121C] text-lg list-decimal ml-4",
    "quote": "text-lg leading-relaxed font-light font-mono text-[#374151] italic border-l-4 border-gray-300 pl-4",
    "callout": "text-lg leading-relaxed font-light font-mono text-[#05121C] p-4 bg-gray-100 rounded",
    "caption": "text-sm font-mono text-gray-500 mt-2 text-center",
    "reference_text": "text-[16px] font-korean font-bold leading-tight tracking-normal mt-0 mb-0 text-left text-[#2A4458] text-[0.85em]",
    "body_ko_default": "text-[clamp(16px,0.45vw+14.55px,20px)] font-korean font-light leading-relaxed tracking-normal mt-2 mb-2 text-left text-[#05121C] break-keep",
    "body_ko_long": "text-[clamp(16px,0.45vw+14.55px,20px)] font-mono font-light leading-loose tracking-normal mt-2 mb-2 text-left text-[#05121C] break-keep",
    "verse_text": "text-[clamp(17px,0.34vw+15.91px,20px)] font-korean font-light leading-relaxed tracking-normal mb-0 text-left text-[#05121C] break-keep",
    "verse_reference": "text-[16px] font-korean font-bold leading-normal tracking-normal mb-1 text-right text-[#2A4458] text-[0.85em]",
    "table_head": "text-[clamp(14px,0.11vw+13.64px,15px)] font-mono font-bold leading-normal tracking-normal mt-0 mb-0 text-left text-[#111827] font-english font-english font-english font-english font-english font-english font-english align-top py-4 px-3",
    "table_cell": "text-[clamp(14px,0.23vw+13.27px,16px)] font-korean font-normal leading-tight tracking-normal mt-0 mb-0 text-left text-[#2a4458] align-top py-4 px-3",
    "link_text": "text-[16px] font-korean font-medium leading-normal tracking-normal mt-0 mb-0 text-left text-[#2a4458] hover:opacity-80 transition-opacity cursor-pointer",
    "footer_contact_label": "font-mono font-bold text-[15px]",
    "footer_contact_value": "font-mono font-light text-[15px]",
    "summary_title": "text-[clamp(20px,1.36vw+15.64px,32px)] font-korean font-bold leading-snug tracking-normal mt-0 mb-0 text-left text-[#05121C] md:"
};

export const cx = (...classes) => classes.filter(Boolean).join(' ');
