'use server';

import fs from 'fs';
import path from 'path';

/**
 * Saves the updated typography config to disk.
 * Note: determining the correct path for development.
 * In Next.js dev, process.cwd() is usually the project root.
 */
export async function saveTypographyConfig(newConfig) {
    try {
        const targetPath = path.join(process.cwd(), 'src/lib/typography-tokens.js');

        // Construct the file content with the new config
        // We preserve the structure of the file but inject new values.
        // For simplicity and robustness, we will rewrite the NEXT_TEXT object.

        const fileContent = `/**
 * Typography Tokens (Interactive)
 * Auto-generated by Type Lab
 */

export const CURRENT_TEXT = ${JSON.stringify(newConfig, null, 4)};

export const NEXT_TEXT = ${JSON.stringify(newConfig, null, 4)};

export const cx = (...classes) => classes.filter(Boolean).join(' ');
`;

        fs.writeFileSync(targetPath, fileContent, 'utf8');
        return { success: true, message: 'Saved successfully to src/lib/typography-tokens.js' };
    } catch (error) {
        console.error("Save failed:", error);
        return { success: false, message: error.message };
    }
}
