'use server';

import fs from 'fs';
import path from 'path';

/**
 * Saves the updated typography config to disk.
 * Note: determining the correct path for development.
 * In Next.js dev, process.cwd() is usually the project root.
 */
export async function saveTypographyConfig(newConfig) {
    try {
        const targetPath = path.join(process.cwd(), 'src/lib/typography-tokens.js');

        // Construct the file content with the new config
        // We preserve the structure of the file but inject new values.
        // For simplicity and robustness, we will rewrite the NEXT_TEXT object.

        const fileContent = `/**
 * Typography Tokens (Interactive)
 * Auto-generated by Type Lab
 */

export const CURRENT_TEXT = {
    // English Display
    hero_en: "text-3xl md:text-4xl font-english font-bold uppercase tracking-widest text-[#05121C]",
    nav_en: "text-sm font-english font-bold tracking-wide uppercase",
    badge: "text-sm font-english font-bold tracking-widest uppercase",

    // Korean Display
    page_title_ko: "text-4xl md:text-5xl lg:text-6xl font-bold font-korean leading-tight break-keep",
    section_title_ko_display: "text-7xl font-bold font-korean leading-none",
    section_heading_ko: "text-2xl font-bold font-mono leading-tight break-keep",

    // Body & Content
    body_ko_default: "text-lg leading-relaxed break-keep font-light font-mono",
    body_ko_long: "text-xl leading-loose break-keep font-light font-mono",

    // Verse
    verse_text: "text-lg leading-relaxed break-keep font-light font-mono",

    // Footer
    footer_contact_label: "font-mono font-bold text-base",
    footer_contact_value: "font-mono font-light text-base",
};

export const NEXT_TEXT = ${JSON.stringify(newConfig, null, 4)};

export const cx = (...classes) => classes.filter(Boolean).join(' ');
`;

        fs.writeFileSync(targetPath, fileContent, 'utf8');
        return { success: true, message: 'Saved successfully to src/lib/typography-tokens.js' };
    } catch (error) {
        console.error("Save failed:", error);
        return { success: false, message: error.message };
    }
}
